**Part 2: Indexing & Slicing (Accessing Your Data)**

**From arr_1d, get the first element.**

In [7]:
import numpy as np
import pandas as pd

ModuleNotFoundError: No module named 'numpy'

SyntaxError: invalid syntax (2071918070.py, line 1)

In [3]:
arr_1d = np.arange(10)
arr_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])

NameError: name 'np' is not defined

In [5]:
You can perform any operation using the imported modules (`numpy`, `pandas`) or the variables already defined (`arr_1d`, `arr_2d`). For example, you can:

- Display the shape of `arr_1d` or `arr_2d`:
    ```python
    arr_1d.shape, arr_2d.shape
    ```

- Calculate the sum or mean of the arrays:
    ```python
    arr_1d.sum(), arr_2d.mean()
    ```

- Convert `arr_2d` to a pandas DataFrame:
    ```python
    pd.DataFrame(arr_2d)
    ```

- Check the data type of the arrays:
    ```python
    arr_1d.dtype, arr_2d.dtype
    ```

Let me know what you want to try!

SyntaxError: invalid syntax (2240190195.py, line 1)

**From arr_1d, get the first element.**

In [ ]:
arr_1d[0]

np.int64(0)

**From arr_1d, get the last element**

In [ ]:
arr_1d[-1]

np.int64(9)

**. From arr_1d, get the elements from index 2 up to index 5**

In [ ]:
arr_1d[2:6]

array([2, 3, 4, 5])

**From arr_1d, get all elements in reverse order.**

In [ ]:
arr_1d[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

**From arr_2d, get the element at row 1, column 2 (which is 6).**

In [ ]:
arr_2d[1, 2]

np.int64(6)

**From arr_2d, get the entire first row [1, 2, 3].**

In [ ]:
arr_2d[0]

array([1, 2, 3])

**From arr_2d, get the entire second column [2, 5, 8]**

In [ ]:
arr_2d[:,1]

array([2, 5, 8])

**. From arr_2d, extract the sub-array [[1, 2], [4, 5]]**

In [ ]:
arr_2d[:2,:2]

array([[1, 2],
       [4, 5]])

**Create a boolean mask to find all numbers in arr_1d that are greater than 5.**

In [ ]:
bool_mask = arr_1d>5
bool_mask

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [ ]:
arr_1d[bool_mask]


array([6, 7, 8, 9])

**Use the boolean mask from the previous question to select the actual numbers from arr_1d**

In [ ]:
arr_1d
mask = arr_1d[bool_mask]
mask

array([6, 7, 8, 9])

**In one line, select all numbers from arr_2d that are odd.**

In [ ]:
bool_index = arr_2d % 2 != 0
bool_index


array([[ True, False,  True],
       [False,  True, False],
       [ True, False,  True]])

In [ ]:
bool_index = arr_2d[bool_index]
bool_index

array([1, 3, 5, 7, 9])

**In arr_1d, replace all values greater than 5 with the value 0.**

In [ ]:
bool_index = arr_1d[arr_1d > 5] = 0 
bool_index
arr_1d

array([0, 1, 2, 3, 4, 5, 0, 0, 0, 0])

**From arr_1d, select the elements at indices 1, 3, and 7.**

In [ ]:
arr_1d

array([0, 1, 2, 3, 4, 5, 0, 0, 0, 0])

In [ ]:
arr_1d = np.arange(10)
selected = arr_1d[[1, 3, 7]]
selected

array([1, 3, 7])

**From arr_2d, select the first and third rows**

In [ ]:
arr_2d[[0, 2]]

array([[1, 2, 3],
       [7, 8, 9]])

**What is the difference between a slice (view) and a fancy index (copy)? Modify a slice ofarr_1d and see if the original changes**

In [ ]:
arr_1d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr_1d = np.arange(10) 
arr_1d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
slice_view = arr_1d[2:5]   
slice_view


array([2, 3, 4])

In [ ]:
slice_view[:] = 99         
slice_view

arr_1d

array([ 0,  1, 99, 99, 99,  5,  6,  7,  8,  9])

In [ ]:
fancy_copy = arr_1d[[1, 3, 5]]
fancy_copy


array([ 1, 99,  5])

In [ ]:
fancy_copy[:] = 77        
fancy_copy



array([77, 77, 77])

In [ ]:
arr_1d

array([ 0,  1, 99, 99, 99,  5,  6,  7,  8,  9])

**Create a copy of arr_2d and modify an element in the copy. Check if the original array is affected.**

In [ ]:
fancy_copy = np.copy(arr_2d)
fancy_copy


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

**From arr_2d, get the diagonal elements [1, 5, 9]**

In [ ]:
np.diag(arr_2d)

array([1, 5, 9])

**Select all rows from arr_2d where the first element is less than 5**

In [ ]:
bool_mask = arr_2d[:, 0] < 5
bool_mask

array([ True,  True, False])

In [ ]:
bool_mask = arr_2d[bool_mask]
bool_mask

array([[1, 2, 3],
       [4, 5, 6]])

**Frm arr_2d, select the elements [2, 4, 9].**

In [ ]:
arr_2d
arr_2d[[0, 1, 2], [1, 0, 2]]

array([2, 4, 9])

**Reverse the order of the rows in arr_2d.**

In [ ]:
arr_2d[::-1]

array([[7, 8, 9],
       [4, 5, 6],
       [1, 2, 3]])