**Part 4: Key Manipulation Techniques**

In [146]:
import numpy as np
import pandas as pd


**56. Reshape the 1D array arr = np.arange(20) into a 4x5 matrix.**

In [147]:
arr = np.arange(20)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [148]:
arr2 = arr.reshape(4,5)

**57. "Flatten" the 2D array matrix = np.array([[1,2],[3,4]]) into a 1D array.**

In [149]:
arr2.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

**59. Transpose a 3x5 matrix into a 5x3 matrix.**

In [150]:
arr2.T

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2,  7, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

**60. Vertically stack the arrays a = np.ones((2,3)) and b = np.zeros((2,3))**


In [151]:
a = np.ones((2,3))
b = np.zeros((2,3))

In [152]:
np.vstack((a,b))

array([[1., 1., 1.],
       [1., 1., 1.],
       [0., 0., 0.],
       [0., 0., 0.]])

**Horizontally stack the arrays a and b.**

In [153]:
np.hstack((a,b))

array([[1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0.]])

**62. Use np.concatenate to achieve the same result as vstack with a and b**

In [154]:
np.concatenate((a,b),axis = 0)

array([[1., 1., 1.],
       [1., 1., 1.],
       [0., 0., 0.],
       [0., 0., 0.]])

**63. Split the array arr = np.arange(10) into 5 equal sub-arrays.
○ Hint: Use np.split().**

In [155]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [156]:

np.split(arr, 5)

[array([0, 1]), array([2, 3]), array([4, 5]), array([6, 7]), array([8, 9])]

**64. Split the 2D array matrix = np.arange(16).reshape(4,4) horizontally into 2 equal arrays.**

In [157]:
matrix = np.arange(16).reshape(4,4)
matrix

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

**65. Insert the value 99 at index 2 in the 1D array arr = np.array([1,2,3,4]).**

In [ ]:
arr = np.array([1,2,3,4])

In [ ]:
np.insert(arr,2,99)

array([ 1,  2, 99,  3,  4])

**Add the value 5 to the end of array arr**

In [ ]:
np.append(arr,5)

array([1, 2, 3, 4, 5])

**67. Get the unique values from the array arr = np.array([1,1,2,3,3,3,4,5]).**

In [ ]:
arr = np.array([1,1,2,3,3,3,4,5])
arr

array([1, 1, 2, 3, 3, 3, 4, 5])

In [ ]:
np.unique(arr)

array([1, 2, 3, 4, 5])

**68. Repeat the array [1,2,3] three times to get [1,2,3,1,2,3,1,2,3]**

In [ ]:
arr= np.array([1,2,3])
arr

array([1, 2, 3])

In [ ]:
arr = np.tile(arr,3)

**70. Flip an array horizontally (left to right).**

In [ ]:
arr = np.array([[1,2,3,4] ,[5,6,7,8]])

In [ ]:
np.fliplr(arr)

array([[4, 3, 2, 1],
       [8, 7, 6, 5]])