In [61]:
import numpy as np
import pandas as pd

Part 7: Practical Applications (Linear Algebra & I/O)


**96. Create a 2x2 matrix A and a 2x2 matrix B. Perform matrix multiplication.**

In [62]:
A = np.arange(1,5) .reshape(2,2)
B = np.arange(5,9) .reshape(2,2)

In [63]:
A@B

array([[19, 22],
       [43, 50]])

**97. Find the inverse of matrix A**

In [64]:
np.linalg.inv(A)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

**98. Find the determinant of matrix B.**

In [65]:
np.linalg.det(B)

np.float64(-2.000000000000005)

**99. Save a NumPy array to a binary file named my_array.npy**

In [66]:
arr = np.array([1, 2, 3, 4, 5])

np.save("my_array.npy", arr)

**100. Load the array from my_array.npy.**

In [67]:

loaded_arr = np.load("my_array.npy")

loaded_arr


array([1, 2, 3, 4, 5])

**101. Save a 2D array to a text file my_matrix.csv with comma-separated values.
 Hint: Use np.savetxt() with the delimiter argumen**

In [68]:
matrix = np.array([[1, 2, 3],[4, 5, 6],  [7, 8, 9]])


np.savetxt("my_matrix.csv", matrix, delimiter=",", fmt="%d")
