**Part 3: Mathematical & Universal Functions (UFuncs)**

In [131]:
import numpy as np
import pandas as pd


**(For questions 36-55, use the following arrays):**

In [132]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])


**36. Add array a and b element-wise**

In [133]:
a+b

array([ 6,  8, 10, 12])

**37. Multiply array a by 3 (scalar multiplication).**

In [134]:
a*3

array([ 3,  6,  9, 12])

**38. Calculate the square of every element in array a.**

In [135]:
a**2

array([ 1,  4,  9, 16])

**Calculate the square root of every element in b.**

In [136]:
np.sqrt(b)

array([2.23606798, 2.44948974, 2.64575131, 2.82842712])

**. Calculate the exponential (e^x) of every element in a.**

In [137]:
np.exp(a)

array([ 2.71828183,  7.3890561 , 20.08553692, 54.59815003])

**. Find the sum of all elements in a.**

In [138]:
sum(a)

np.int64(10)

**42. Find the mean of all elements in b.**

In [139]:
b.mean()

np.float64(6.5)

**43. Find the maximum value in a.**

In [140]:
a.max()

np.int64(4)

**44. Find the minimum value in b.**

In [141]:
b.min()

np.int64(5)

**45. Given a 2D array matrix = np.arange(12).reshape(3, 4), find the sum of all its elements**

In [142]:
d_arr =np.arange(12) .reshape(3,4)
d_arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [143]:
d_arr.sum()

np.int64(66)

**46. For the matrix, find the sum of each column**

In [144]:
d_arr.sum(axis=0)

array([12, 15, 18, 21])

**47. For the matrix, find the mean of each row**

In [145]:
d_arr.sum(axis=1)

array([ 6, 22, 38])

**48. For the matrix, find the minimum value in each row.**

In [146]:
d_arr.min(axis=1)

array([0, 4, 8])

**49. Create a new array by finding which element is larger at each position between a and b.**

In [147]:
np.maximum(a,b)

array([5, 6, 7, 8])

**50. Round all values in the array arr_float = np.array([1.5, 2.3, 3.8]) to the nearest integer**

In [148]:
arr_float = np.array([1.5, 2.3, 3.8]) 
arr_float

array([1.5, 2.3, 3.8])

In [149]:
np.round(arr_float)

array([2., 2., 4.])

**51. Calculate the standard deviation of array a.**

In [150]:
np.std(a)

np.float64(1.118033988749895)

**52. Calculate the cumulative sum of a. The result should be [1, 3, 6, 10].**

In [151]:
np.cumsum(a)

array([ 1,  3,  6, 10])

**53. Compare arrays a and b to see if they are equal element-wise.**

In [152]:
ar = a==b
ar

array([False, False, False, False])

**54. Check if any element in the result of a > 2 is True.**

In [153]:
(a>2).any()

np.True_

**55. Check if all elements in b are greater than 4.**

In [154]:
(b>4).all()

np.True_