In [108]:
import numpy as np
import pandas as pd

**Part 5: Broadcasting & Conditional Logic**

**71. Add a 1D array v = np.array([1, 2, 3]) to each row of a 2D array M = np.ones((4,3)). What is
this concept called?**

In [109]:
v = np.array([1, 2, 3]) 
M = np.ones((4,3))


In [110]:
M+v

array([[2., 3., 4.],
       [2., 3., 4.],
       [2., 3., 4.],
       [2., 3., 4.]])

**Can you add a (3,3) matrix and a (3,) vector? If so, how does it work?**

In [111]:
A = np.arange(9) .reshape(3,3)
A

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [112]:
v = ([10,20,30])

In [113]:
A+v

array([[10, 21, 32],
       [13, 24, 35],
       [16, 27, 38]])

**73. Can you add a (3,3) matrix and a (3,1) matrix?**

In [114]:
A


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [115]:
B= np.arange(3).reshape(3,1)

In [116]:
B

array([[0],
       [1],
       [2]])

In [117]:
A+B

array([[ 0,  1,  2],
       [ 4,  5,  6],
       [ 8,  9, 10]])

**74. Create a 1D array arr = np.arange(10). Use np.where to create a new array where values are 0
if the original value was less than 5, and the original value otherwise.**

In [118]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [119]:
np.where(arr < 5, 0, arr)

array([0, 0, 0, 0, 0, 5, 6, 7, 8, 9])

**75. Use np.where to create a new array from arr where even numbers are replaced by 0 and odd
numbers by 1.**

In [120]:
np.where(arr%2==0,0,1)

array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1])

**76. Create a 5x5 array of random integers. Use np.where to replace all values greater than 50 with
the value 50.**

In [121]:
arr = np.arange(45,70).reshape(5,5)
arr

array([[45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64],
       [65, 66, 67, 68, 69]])

In [122]:
np.where(arr > 50, 50, arr)

array([[45, 46, 47, 48, 49],
       [50, 50, 50, 50, 50],
       [50, 50, 50, 50, 50],
       [50, 50, 50, 50, 50],
       [50, 50, 50, 50, 50]])

**77. Create a 1D array from 1 to 10. Extract all numbers that are either less than 3 or greater than
8.**

In [123]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [124]:
arr[(arr<3)|(arr>8)]

array([ 1,  2,  9, 10])

**78. What will be the result of adding a (4,1) array to a (1,5) array?**

In [125]:


a = np.arange(1, 5).reshape(4, 1)   
b = np.arange(10, 15).reshape(1, 5) 

result = a + b
result.shape


(4, 5)

**Q79. Normalize a 5x5 random matrix**

In [126]:
M = np.random.rand(5, 5)   

mean = M.mean()
std = M.std()

normalized = (M - mean) / std
normalized


array([[-1.18895701, -1.10591783, -1.36729778, -1.09829745,  0.02404717],
       [-0.42820396,  0.1976427 ,  1.8145447 , -0.96027964,  0.57193611],
       [-0.55470967,  1.19866104, -0.12377032, -0.14559456,  1.67735554],
       [ 1.42057663, -0.32198491,  1.7383779 ,  0.61760358,  0.04173211],
       [-0.54705855, -1.30570804,  0.63257595,  0.52483265, -1.31210634]])

In [127]:
M

array([[0.1150935 , 0.13778286, 0.06636424, 0.13986502, 0.44653087],
       [0.32295922, 0.49396356, 0.93576068, 0.17757657, 0.59623429],
       [0.28839321, 0.7674786 , 0.40614169, 0.40017851, 0.89827556],
       [0.82811411, 0.35198218, 0.91494911, 0.60871232, 0.45136305],
       [0.29048378, 0.08319282, 0.61280333, 0.58336389, 0.08144457]])

**Q80. From 1D array → 2D array with rows as copies**

In [128]:
arr = np.array([1, 2, 3, 4])

result1 = np.tile(arr, (3, 1))  

result2 = np.zeros((3, arr.size)) + arr

result1

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4]])

In [129]:
result2

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])