**1. Import the NumPy library with the alias np.**
**

In [1]:
import numpy as np

**Create a 1D NumPy array from the Python list [1, 2, 3, 4, 5]**

In [2]:
list = np.array([1,2,3,4,5])
list

array([1, 2, 3, 4, 5])

**Create a 1D array of 10 zeros**

In [3]:
zeros = np.zeros(10)
zeros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

**Create a 3x3 array filled with ones**

In [4]:
ones = np.ones(9).reshape(3,3)
ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

**Create an array of all even integers from 10 to 50.**

In [5]:
arr = np.arange(10,51)
arr
even = arr[::2]
even

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

**Create a 3x3 matrix with values ranging from 0 to 8.**

In [6]:
arr = np.arange(0,9) .reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [7]:
arr = np.eye(4,4)
arr

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

**Create an array of 5 numbers evenly spaced between 0 and 1.**

In [8]:
arr =np.linspace(0,1,5)
arr 

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

**Create a 3x4 array filled with random numbers between 0 and 1.**

In [9]:
arr = np.random.rand(3,4)
arr 



array([[0.92572891, 0.75644616, 0.43624263, 0.00189627],
       [0.7647522 , 0.23363317, 0.40332993, 0.68799057],
       [0.01892908, 0.15579805, 0.58730509, 0.59740561]])

**Create a 5x5 array with random integers from 1 to 100.**

In [10]:
arr = np.random.randint(1,101, size = (5,5))
arr

array([[79, 83, 17, 84, 26],
       [82, 10, 88, 34, 16],
       [ 2, 60, 64, 65, 58],
       [82, 30, 57, 52, 53],
       [61, 27, 76, 13,  2]], dtype=int32)

**Given the array arr = np.arange(25).reshape(5, 5), find its shape**

In [11]:
arr = np.arange(25).reshape(5, 5)
arr.shape

(5, 5)

**For the same array arr, find its data type.**

In [12]:
arr = np.arange(25).reshape(5, 5)
print(arr.shape)

arr2= arr.dtype
arr2

(5, 5)


dtype('int64')

**For the same array arr, find the total number of elements.**

In [13]:
arr3 = arr.size
arr3

25

**Create the array [1, 2, 3] but make sure its data type is float.**

In [14]:
arr = np.array((1,2,3), dtype=float)
arr

array([1., 2., 3.])

**Convert the data type of an existing integer array to float**

In [15]:
arr = np.array([1,2,3,4,5,])
float_arr = arr.astype(float)
d_type = float_arr.dtype
d_type
float_arr


array([1., 2., 3., 4., 5.])