**1. Import the NumPy library with the alias np.**
**

In [52]:
import numpy as np

**Create a 1D NumPy array from the Python list [1, 2, 3, 4, 5]**

In [53]:
list = np.array([1,2,3,4,5])
list

array([1, 2, 3, 4, 5])

**Create a 1D array of 10 zeros**

In [54]:
zeros = np.zeros(10)
zeros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

**Create a 3x3 array filled with ones**

In [55]:
ones = np.ones(9).reshape(3,3)
ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

**Create an array of all even integers from 10 to 50.**

In [56]:
arr = np.arange(10,51)
arr
even = arr[::2]
even

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

**Create a 3x3 matrix with values ranging from 0 to 8.**

In [57]:
arr = np.arange(0,9) .reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [58]:
arr = np.eye(4,4)
arr

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

**Create an array of 5 numbers evenly spaced between 0 and 1.**

In [59]:
arr =np.linspace(0,1,5)
arr 

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

**Create a 3x4 array filled with random numbers between 0 and 1.**

In [60]:
arr = np.random.rand(3,4)
arr 



array([[0.3916455 , 0.64169205, 0.07536445, 0.75160161],
       [0.04100611, 0.53637295, 0.82493557, 0.14799973],
       [0.02181621, 0.68100354, 0.10368862, 0.31516479]])

**Create a 5x5 array with random integers from 1 to 100.**

In [61]:
arr = np.random.randint(1,101, size = (5,5))
arr

array([[64, 43, 81, 10, 84],
       [56, 83, 41, 41, 65],
       [ 7, 46, 98, 95, 20],
       [10,  8, 84, 22, 86],
       [65,  3, 77, 15, 28]], dtype=int32)

**Given the array arr = np.arange(25).reshape(5, 5), find its shape**

In [62]:
arr = np.arange(25).reshape(5, 5)
arr.shape

(5, 5)

**For the same array arr, find its data type.**

In [63]:
arr = np.arange(25).reshape(5, 5)
print(arr.shape)

arr2= arr.dtype
arr2

(5, 5)


dtype('int64')

**For the same array arr, find the total number of elements.**

In [64]:
arr3 = arr.size
arr3

25

**Create the array [1, 2, 3] but make sure its data type is float.**

In [65]:
arr = np.array((1,2,3), dtype=float)
arr

array([1., 2., 3.])

**Convert the data type of an existing integer array to float**

In [68]:
arr = np.array([1,2,3,4,5,])
float_arr = arr.astype(float)
d_type = float_arr.dtype
d_type
float_arr


array([1., 2., 3., 4., 5.])