**Part 6: Statistics, Sorting, & Searching**


In [315]:
import pandas as pd
import numpy as np

**81. Create a 1D array of 10 random integers and sort it in ascending order.**

In [316]:
M = np.random.randint(1,100 ,size =10)
M

array([17, 31, 19, 49, 51, 72, 39, 23, 95, 22], dtype=int32)

In [317]:
sorted_M = np.sort(M)

In [318]:
sorted_M

array([17, 19, 22, 23, 31, 39, 49, 51, 72, 95], dtype=int32)

**83. Find the indices that would sort the array arr = np.array([3, 1, 4, 2]).**

In [319]:
arr = np.array([3, 1, 4, 2])
arr

array([3, 1, 4, 2])

In [320]:
np.argsort(arr)

array([1, 3, 0, 2])

**84. Find the index of the maximum value in arr.**

In [321]:
arr.argmax()

np.int64(2)

**85. Find the index of the minimum value in arr.**

In [322]:
np.argmin(arr)

np.int64(1)

**86. In a 2D array, find the index of the maximum value in each column**

In [323]:
np.argmax(arr , axis = 0)

np.int64(2)

**. Find the unique values and their counts in the array arr = np.array([1, 2, 2, 3, 3, 3, 1]).**

In [324]:
arr = np.array([1, 2, 2, 3, 3, 3, 1])

In [325]:
np.unique(arr , return_counts=1)

(array([1, 2, 3]), array([2, 2, 3]))

**88. Find the common elements between two arrays a = np.array([1,2,3]) and b = np.array([2,3,4])**

In [326]:
a = np.array([1,2,3])
b = np.array([2,3,4])


In [327]:
np.intersect1d(a,b)

array([2, 3])

**89. Find the elements in a that are not in b**

In [328]:
np.setdiff1d(a,b)

array([1])

**90. Sort a 2D array based on its second column.**

In [329]:
arr = np.array([[5, 2, 8],[3, 1, 6],[9, 4, 7]])

In [330]:
arr

array([[5, 2, 8],
       [3, 1, 6],
       [9, 4, 7]])

In [331]:
indices = arr[:, 1].argsort()
sorted_arr = arr[indices]

In [332]:
arr

array([[5, 2, 8],
       [3, 1, 6],
       [9, 4, 7]])

In [333]:
sorted_arr

array([[3, 1, 6],
       [5, 2, 8],
       [9, 4, 7]])

91. Find the 50th percentile (median) of a random array

In [334]:
arr = np.random.randint(1, 100, size=15)
arr

array([17, 17, 37, 25, 28, 81, 16, 66, 13, 96, 47, 60, 52,  1, 53],
      dtype=int32)

In [335]:
p50 = np.percentile(arr, 50)
median = np.median(arr)

In [336]:
p50

np.float64(37.0)

In [337]:
median

np.float64(37.0)

**92. Find the 25th and 75th percentiles of an array.
○ Hint: Pass a list of percentiles: np.percent**

In [338]:
arr

array([17, 17, 37, 25, 28, 81, 16, 66, 13, 96, 47, 60, 52,  1, 53],
      dtype=int32)

In [339]:
p25 = np.percentile(arr, 25)
p75 =np.percentile(arr, 75)
median1 = np.median(arr)

In [340]:
np.percentile(arr, [25, 75])


array([17. , 56.5])

In [341]:
median1

np.float64(37.0)

**93. Find all non-zero elements in the array [1, 0, 2, 0, 3].
○ Hint: Use np.nonzero().**

In [342]:
arr =np.array([1, 0, 2, 0, 3])
arr

array([1, 0, 2, 0, 3])

In [343]:
np.nonzero(arr)

(array([0, 2, 4]),)

**94. Check which elements of array a are present in array b.
○ Hint: Use np.in1d().**

In [344]:


a = np.array([1, 2, 3, 4, 5])
b = np.array([2, 4, 6, 8])

mask = np.isin(a, b)

mask          
a[mask]


array([2, 4])

**5. Find the top 3 largest values from a 1D array.
○ Hint: Sort the array and take the last 3 elements.**

In [345]:

arr = np.array([12, 45, 7, 89, 34, 23, 90, 56])

sorted_arr = np.sort(arr)

top3 = sorted_arr[-3:]

arr



array([12, 45,  7, 89, 34, 23, 90, 56])

In [346]:
top3

array([56, 89, 90])